title:               How to manage money?
description:         Discover the smarter way to manage your finances
author:              Chris Sobolewski
include:             ['_pages']

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
#  - jekyll-feed

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
